fqdn = "mail.example.com"
sending_fqdn = "example.com"

domains = ["localhost"]

enable_smtp = true
enable_pop3 = false

[[accounts]]
domain = "localhost"
user = "me"
aliases = []

[[accounts]]
domain = "sean.cyou"
user = "me"
aliases = ["hi@sean.cyou"]
